[project]
name = "rapidapi-linkedin-mcp"
version = "0.1.0"
description = "A MCP server to access the LinkedIn API through RapidAPI, based on the FastMCP framework."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.8.0",
]